spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/flyway_test
    username: root
    password: P@s4mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

my:
  entityname: STUDENT
  entity:
    names:
      subject: SUBJECT
  export:
    file:
      path: D:\dbExport
      name:
        txt: students.txt
        csv: students.csv
        xlsx: students.xlsx
